In [4]:
#Creating a NumPy array
import numpy as np

array = np.array([5, 10, 15, 20, 25])

print("Elements in array:", array)

Elements in array: [ 5 10 15 20 25]


In [5]:
#Array Operating: Let's find average of above aaray elements
average = np.mean(array)
print("Average of above array is:", average)

Average of above array is: 15.0


In [6]:
#Multi Dimentional Array
height_cm = np.array([[100,120,111], [110, 105, 120], [120, 115, 130]])
print("Heights of students:", height_cm)

Heights of students: [[100 120 111]
 [110 105 120]
 [120 115 130]]


In [16]:
#Array Indexing and Slicing
first_bench_student_height = height_cm[0]
print("First bench Student height:", first_bench_student_height)

student_height = height_cm[1][2]
print("Student height is:", student_height)

last_bench_height = height_cm[:-1]
print("Last bench student height:", last_bench_height)

First bench Student height: [100 120 111]
Student height is: 120
Last bench student height: [[100 120 111]
 [110 105 120]]


In [21]:
#Let's convert the temperature from celcius into fraenheight
temperature = np.array([[20, 25, 29], [19, 23, 22], [18, 20, 37]])
f = (temperature * 9/5) + 32
print("Temperaute in fraenheight is:\n", f)

k = (temperature + 273.15)
print("Temperaute in Kelvin is:\n", k)

Temperaute in fraenheight is:
 [[68.  77.  84.2]
 [66.2 73.4 71.6]
 [64.4 68.  98.6]]
Temperaute in Kelvin is:
 [[293.15 298.15 302.15]
 [292.15 296.15 295.15]
 [291.15 293.15 310.15]]


In [24]:
#Linera Algebra
sales = np.array([[500, 100, 200], [750, 1000, 1500]])
quantity = np.array([[10, 20, 30], [100, 200, 50]])

revenue = np.dot(sales, quantity.T)
print("Total Revenue:\n", revenue)

Total Revenue:
 [[ 13000  80000]
 [ 72500 350000]]


In [33]:
#Zeros and ones (matrix)

#Zeros
print("Zeros Matrix 3x3 is:\n", np.zeros((3,3), dtype = int))

#Ones
print("Ones Matrix 3x3 is:\n", np.ones((3,3), dtype = int))

#Zeros and Ones
print("Ones Matrix 5x5 is:\n", np.eye(5, dtype = int))


Zeros Matrix 3x3 is:
 [[0 0 0]
 [0 0 0]
 [0 0 0]]
Ones Matrix 3x3 is:
 [[1 1 1]
 [1 1 1]
 [1 1 1]]
Ones Matrix 5x5 is:
 [[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [39]:
#Creating a 1D NumPy array values ranging from 0 to 9
array_1D = np.arange(10)
print("1D array:\n",array_1D)

#Create a 2D NumPy array with the shape (3,3) containing values from 0 to 9
array_2D = np.arange(1, 10).reshape(3,3)
print("\n 2D Array:\n", array_2D)

1D array:
 [0 1 2 3 4 5 6 7 8 9]

 2D Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [40]:
#Perform element-wise addition, subtracion, multiplication and division
array1 = np.array([1,2,3])
array2 = np.array([4,5,6])

addition = array1 + array2
subtraction = array1 - array2
multiplication = array1 * array2
division = array1 / array2

print(addition, subtraction, multiplication, division)

[5 7 9] [-3 -3 -3] [ 4 10 18] [0.25 0.4  0.5 ]
